[package]
name = "fastai-lesson4-patent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { version = "0.30.0", features = ["lazy", "csv", "concat_str"] }
